name: shop_it_all
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wishlist to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.6.0
  rxdart: ^0.28.0
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.3.3
  skeletonizer: ^1.4.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  mocktail: ^1.0.4


flutter:

  uses-material-design: true

  assets:
    - assets/images/category_images/
    - assets/images/random_images/
    - assets/images/product_images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
